### ISSUE TITLE
NASM Still Listed In Project Files

### ISSUE THREAD

**Issue by steven-schronk** [steven-schronk/Kkrieger-Werkkzeug3#1]
Have to build in Release mode to get the build to fail.

Looks like this is still in the .vcproj files.

https://github.com/steven-schronk/Kkrieger-Werkkzeug3/blob/3884b622758863ffe269aaf8f0f915c3bb4d2921/werkkzeug3_kkrieger/werkkzeug3/werkkzeug3.vcxproj#L126

**Comment by LWP-GH** [comment]
I guess visual studio doesn't consider these files as a part of the solution. Searched the whole file tree and replaced every nasm with yasm. The only nasm commands I left in were a part of the yasm mkfiles. I assume yasm needs those to stay the same.
